apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer2-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
  volumeName: "pvc-7a23d7cf-aff6-478e-917e-df7910c5a720"